# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: efa50da582b46de8e07fd90d6a7f4888b5efb612ad9c965b82ec08831aa0f47e3e28b9e7dbba132caa85e45acf0fbb97cb84e7ee9d892dede244ae0df56d287e

test:
  secret_key_base: cf10334853271a019e0ea60852147c8aafbfba75322ec63857cbb21bfe7463401306a9eeb14c939548db2cdd0a2dc467b738524aa4ced7bc6acfb4121369c57e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
